remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Daniella Milani's Portfolio
description: Professional with more than 10 years of experience in Financial Services. Recently transitioned her career to Technology and Data, currently developing her technical skills in SQL, Python and Data Visualization.
